MONGODB_HOST: "mongodb-{{environment}}.darlavinaykumar.fun"
REDIS_HOST: "redis-{{environment}}.darlavinaykumar.fun"
MYSQL_HOST: "mysql-{{environment}}.darlavinaykumar.fun"
RABBITMQ_HOST: "rabbitmq-{{environment}}.darlavinaykumar.fun"
USER_HOST: "user-{{environment}}.darlavinaykumar.fun"
CART_HOST: "cart-{{environment}}.darlavinaykumar.fun"
PAYMENT_HOST: "payment-{{environment}}.darlavinaykumar.fun"
SHIPPING_HOST: "shipping-{{environment}}.darlavinaykumar.fun"
CATALOGUE_HOST: "catalogue-{{environment}}.darlavinaykumar.fun"