MONGODB_HOST: "mongodb-{{environment}}.darlavinaykumar.fun"
REDIS_HOST: "redis-{{environment}}.darlavinaykumar.fun"
MYSQL_HOST: "mysql-{{environment}}.darlavinaykumar.fun"
RABBITMQ_HOST: "rabbitmq-{{environment}}.darlavinaykumar.fun"
USER_HOST: "user.backend-alb-{{environment}}.darlavinaykumar.fun"
CART_HOST: "cart.backend-alb-{{environment}}.darlavinaykumar.fun"
PAYMENT_HOST: "payment.backend-alb-{{environment}}.darlavinaykumar.fun"
SHIPPING_HOST: "shipping.backend-alb-{{environment}}.darlavinaykumar.fun"
CATALOGUE_HOST: "catalogue.backend-alb-{{environment}}.darlavinaykumar.fun"